services:
  vite-portfolio:
    container_name: vite-portfolio
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src      
      - ./dist:/app/dist      
      - ~/.ssh/ak2024_v1:/root/.ssh/id_rsa:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
    stdin_open: true
    tty: true