services:
  vite-portfolio:
    container_name: vite-portfolio
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.ssh/ak2024_v1:/root/.ssh/id_rsa:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
    stdin_open: true
    tty: true